### PR TITLE
Upgrade Camel Version to pull in Extensions #59

### PR DESCRIPTION
**Pull request by lburgazzoli**
@KurtStam @jimmibot @zregvart 

First bits to upgrade to Camel 2.20, notes:

-  I've bumped camel to 2.20.0-SNAPSHOT as I had to make some fixes upstream so a new fuse build is needed.
- For component based on official Camel components, I've added the suffix ``-connector`` to the scheme to avoid conflicts i.e. there is now a ``twitter-search`` scheme upstream so here we have a`` twitter-search-connector`` here; I left untouched ``trade-*`` connectors but maybe it would be better to follow a common pat and have all the schemes ending with ``-connector``.

### CODE REVIEW

**Comment by zregvart** [comment]
@lburgazzoli perhaps we can depend on Fuse early access builds, we do in `syndesis-verifier` (https://github.com/syndesisio/syndesis-verifier/blob/master/pom.xml#L75-L87) and we need to for #60

**Comment by lburgazzoli** [comment]
Don but it does not yet have a version with required bits

**Comment by zregvart** [comment]
> Don but it does not yet have a version with required bits

There is also `2.20.0.fuse-000093` built yesterday I guess that should be recent enough?

**Comment by lburgazzoli** [comment]
Ah yeah, didn't spot it (don't know why)

**Review by zregvart — APPROVED** [review]
👍

**Pull request merged**
