### PR TITLE
Initial version of json based salesforce-sobject connectors Fixes issue #32

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dhirajsb** [comment]
@zregvart can you review this? Just has connectors, still trying to get example to work on 2.19.3-SNAPSHOT, working on resolving errors from using connector configurations for setting underlying component name

**Comment by dhirajsb** [comment]
Looks like build is failing since `rawPayload` option is only afaik in 2.19.3-SNAPSHOT right now. Might need to let SNAPSHOTs in or do another Camel release??

**Comment by zregvart** [comment]
@dhirajsb you can try using Camel `2.20.0.fuse-000091` from JBoss early access repository we do that in the verifier https://github.com/syndesisio/syndesis-verifier/blob/master/pom.xml#L75-L87

**Review by zregvart — DISMISSED** [review]
extra cool, thanks 👍

**Comment by dhirajsb** [comment]
@zregvart looks like the CircleCI build doesn't use RedHat repos??

**Comment by zregvart** [comment]
> @zregvart looks like the CircleCI build doesn't use RedHat repos??

@dhirajsb you can add `<repositories>` block like we do in https://github.com/syndesisio/syndesis-verifier/blob/master/pom.xml#L75-L87

**Comment by zregvart** [comment]
I think we need #61 merged and this rebased on that to make it work.

**Review by zregvart — APPROVED** [review]
:+1:

**Pull request merged**
